steps:
  - label: ":hammer: running tests"
    commands:
      - "make ci"
        #- "make test" #currently no ct defined, causes build error
    key: "tests"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^otp/
    label: ":debian: build deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh prod"
    key: "deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^otp/
    label: "upload"
    name: ":cloud: upload to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "deb"
    agents:
      queue: "erlang"

  - if: build.tag != null && build.tag !~ /^otp/
    label: "prod docker"
    name: ":whale: build docker prod image"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_docker.sh docker_node"
    agents:
      queue: "erlang"
